[project]
name = "mlipts"
version = "0.1.0"
description = "MLIPTS: Machine Learning Interatomic Potentials Training Suite"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]